# ==========================================================
# Copyright (c) 2026 ArtistBots
# All Rights Reserved. 
#
# Project      : ArtistBots API Telegram Music Bot
# Powered By   : Artist
# Type         : API Based Telegram Music Bot
#
# Bot          : @ArtistApibot
# Channel      : https://t.me/artistbots
# GitHub       : https://github.com/elevenyts/ArtistMusic
#
# Unauthorized copying, modification, or redistribution
# of this source code without permission is prohibited.
# ==========================================================
services:
  - type: worker
    name: ArtistMusic
    runtime: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python -m ArtistMusic
    plan: free
