import asyncio
import logging

from pyrogram import filters
from pyrogram.enums import ParseMode
from pyrogram.handlers import MessageHandler

import state
from clients import user_app, call_py

logger = logging.getLogger(__name__)


async def _is_assistant_member(chat_id):
    """Check membership using the assistant user session itself."""
    if not state.ASSISTANT_ID:
        return False
    try:
        member = await user_app.get_chat_member(chat_id, state.ASSISTANT_ID)
        status = getattr(member, "status", None)
        # Pyrogram statuses include member/administrator/owner and can vary by version.
        return str(status).lower() not in {"banned", "left", "kicked", "none"}
    except Exception:
        return False


async def ensure_assistant_in_group(client, chat_id):
    """Ensure the user-session assistant is a member of the group.

    For private groups the most reliable path is the bot directly adding the
    assistant user. Telegram requires the bot to have the appropriate
    "Invite Users via Link" / invite-users admin right for this operation.
    Public groups can also be joined through their username.
    """
    if await _is_assistant_member(chat_id):
        state.assistant_join_error = None
        return True

    assistant_id = state.ASSISTANT_ID
    if not assistant_id:
        state.assistant_join_error = "Assistant session is not ready."
        return False

    # 1) Private/public groups: let the bot add the assistant directly.
    try:
        await client.add_chat_members(chat_id, assistant_id, forward_limit=0)
        await asyncio.sleep(1)
        if await _is_assistant_member(chat_id):
            state.assistant_join_error = None
            logger.info("Assistant %s added to chat %s", assistant_id, chat_id)
            return True
    except Exception as exc:
        text = str(exc)
        lower = text.lower()
        state.assistant_join_error = text
        logger.warning("Direct assistant add failed for %s: %s", chat_id, exc)
        if "invite" in lower or "admin" in lower or "permission" in lower:
            state.assistant_join_error = (
                "The bot needs the Telegram admin permission to invite/add users."
            )

    # 2) Public group fallback: assistant can join by username.
    try:
        chat = await client.get_chat(chat_id)
        username = getattr(chat, "username", None)
        if username:
            try:
                await user_app.join_chat(f"https://t.me/{username}")
            except Exception as exc:
                text = str(exc).lower()
                if "already" not in text and "participant" not in text:
                    logger.warning("Assistant public join failed for %s: %s", chat_id, exc)
            await asyncio.sleep(1)
            if await _is_assistant_member(chat_id):
                state.assistant_join_error = None
                return True
    except Exception as exc:
        logger.warning("Public-group assistant join fallback failed: %s", exc)

    # 3) Private-group fallback: create/use an invite link generated by THIS bot.
    # This only works when the bot is an admin with invite-users permission.
    try:
        invite_link = await client.export_chat_invite_link(chat_id)
    except Exception:
        try:
            link_obj = await client.create_chat_invite_link(chat_id)
            invite_link = link_obj.invite_link
        except Exception as exc:
            logger.warning("Could not create a bot-owned invite link for %s: %s", chat_id, exc)
            invite_link = None

    if invite_link:
        try:
            await user_app.join_chat(invite_link)
        except Exception as exc:
            text = str(exc).lower()
            if "already" not in text and "participant" not in text:
                logger.warning("Assistant invite-link join failed for %s: %s", chat_id, exc)
        await asyncio.sleep(1)
        if await _is_assistant_member(chat_id):
            state.assistant_join_error = None
            return True

    if not state.assistant_join_error:
        state.assistant_join_error = (
            "Assistant is not a member. Add the assistant once or give the bot invite-users permission."
        )
    return False


async def voice_chat_started(client, message):
    chat_id = message.chat.id
    try:
        joined = await ensure_assistant_in_group(client, chat_id)
        if joined:
            text = "😍 <b>ᴠɪᴅᴇᴏ ᴄʜᴀᴛ sᴛᴀʀᴛᴇᴅ🥳</b>\n🎙️ <i>Music assistant is ready.</i>"
        else:
            text = (
                "😍 <b>ᴠɪᴅᴇᴏ ᴄʜᴀᴛ sᴛᴀʀᴛᴇᴅ🥳</b>\n"
                "⚠️ <i>Assistant could not be added automatically.</i>\n\n"
                "Give the bot <b>Invite Users via Link</b> admin permission, "
                "or add the assistant account to this group once."
            )
        await message.reply_text(text, parse_mode=ParseMode.HTML)
    except Exception as exc:
        logger.exception("Voice-chat start handler failed: %s", exc)


async def voice_chat_ended(client, message):
    chat_id = message.chat.id

    task = state.progress_tasks.pop(chat_id, None)
    if task:
        task.cancel()

    queue = state.chat_queues.pop(chat_id, [])
    for item in queue:
        path = item.get("file_path") if isinstance(item, dict) else None
        if path:
            try:
                import os
                if os.path.exists(path):
                    os.remove(path)
            except Exception:
                pass

    state.paused_chats.discard(chat_id)

    try:
        await call_py.leave_call(chat_id)
    except Exception:
        pass

    await message.reply_text(
        "😕 <b>ᴠɪᴅᴇᴏ ᴄʜᴀᴛ ᴇɴᴅᴇᴅ💔</b>\n"
        "🗑️ <b>Queue and playback records have been cleared.</b>",
        parse_mode=ParseMode.HTML,
    )


def register_voice_handlers(client):
    client.add_handler(MessageHandler(voice_chat_started, filters.video_chat_started & filters.group))
    client.add_handler(MessageHandler(voice_chat_ended, filters.video_chat_ended & filters.group))
