services:
  - type: web
    name: kust-music-bot
    env: python
    plan: free
    buildCommand: "apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ASSISTANT_SESSION
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SEARCH_API_URL
        sync: false
      - key: DOWNLOAD_API_BASE
        sync: false
      - key: YOUTUBE_COOKIES
        sync: false
